spring:
  application:
    name: spring-music
  jpa:
    generate-ddl: true
  resources:
    add-mappings: true
  mvc:
    throw-exception-if-no-handler-found: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
